stages:
  - test
  - package
  - deploy


# To make gitlab shut the fuck up about never completing pipelines
dummy_success_job:
  stage: test
  script:
    - echo "Dummy always passes"


containerize:
  stage: package
  image: docker:24.0.5-dind
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker compose build
    - docker compose push
  after_script:
    - docker rmi ${CI_REGISTRY_IMAGE}/server:latest
    - docker rmi ${CI_REGISTRY_IMAGE}/frontend:latest


deploy:
  stage: deploy
  image: alpine:latest
  only:
    - main
  before_script:
    - apk add --no-cache openssh bash
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY_B64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - |
      cat > ~/.ssh/config <<'EOF'
      Host *
        StrictHostKeyChecking no
      EOF
  script:
    - echo "[+] SSH and run last-mile deployment"
    - |
      ssh "$SERVER_USER@$SERVER_IP" <<'EOF'
      cd deployment
      ./last-mile-deployment.sh
      EOF

