services:
  server:
    build:
      dockerfile: Dockerfile
      context: server
    environment:
      - ALLOWED_ORIGINS=http://frontend:3000
    ports:
      - 8000:8000

  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://server:8000      
    ports:
      - 3000:3000