services:
  server:
    image: ${CI_REGISTRY_IMAGE}/server:latest
    build:
      dockerfile: Dockerfile
      context: server
    environment:
      - ALLOWED_ORIGIN=http://frontend:3000
    ports:
      - 8000:8000

  frontend:
    image: ${CI_REGISTRY_IMAGE}/frontend:latest
    build:
      dockerfile: Dockerfile
      context: frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    ports:
      - 3000:3000